image:
  repository: "quay.io/backstage-performance/locust-k8s-operator"
  tag: "latest"
  pullPolicy: Always

k8s:
  clusterRole:
    enabled: true

locustPods:
  resource:
    request:
      cpu: 250m
      memory: 256Mi
      ephemeralStorage: 30Mi
    limits:
      cpu: 250m
      memory: 256Mi
      ephemeralStorage: 100Mi
  metricsExporter:
    image: "quay.io/backstage-performance/locust_exporter:latest"
    pullPolicy: Always

serviceAccount:
  name: ${LOCUST_NAMESPACE}-locust-k8s-operator
